name: Wait for CMS to be ready
description: Pause until we know that the CMS is online and ready to go

inputs:
  base_url:
    description: Base url for the cms environment to wait for
    required: false
    default: 'https://prod.cms.va.gov'
  interval:
    description: How often to poll the environment for status (in seconds)
    required: false
    default: '15'
  timeout:
    description: How long should we wait for the cms to be ready (in seconds)
    required: false
    default: '4200'

runs:
  using: composite
  steps:
    - name: Wait for CMS to be ready
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        timer=0

        while true
        do
          if [ $timer -gt ${{ inputs.timeout }} ]; then
            echo "Timeout exceeded."
            exit 1
          fi

          if [[ "$(curl -s -o /dev/null -w '%{http_code}' ${{ inputs.base_url }})" != "200" ]]; then
            sleep ${{ inputs.interval }}
            timer=$(($timer + ${{ inputs.interval }}))
          else
            echo "Ready!"
            break
          fi
        done
