name: 'Close stale PRs'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
      with:
        stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. It will be closed in 7 days if it does not recieve a comment or if the stale label is not removed.'
        days-before-pr-stale: 30
        days-before-pr-close: 7