name: 'Close stale PRs'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-pr-message: 'This PR is stale because it has been open 120 days with no activity. It will be closed in 7 days if it does not recieve a comment or if the stale label is not removed.'
          days-before-pr-stale: 120
          days-before-pr-close: 7
          close-pr-label: 'do not archive'
