name: ZZ Content Release Workflow testing

on:
  workflow_dispatch:
  pull_request:

  # repository_dispatch:
  #   types: [content-release]

concurrency:
  group: content-release-prod-testing

env:
  CMS_NOTIFICATIONS_SLACK: CJT90C0UT # cms-notifications
  VFS_PLATFORM_BUILDS_SLACK: C0MQ281DJ # vfs-platform-builds
  BROKEN_LINKS_SLACK: C030F5WV2TF # content-broken-links
  CONTENT_BUILD_CHANNEL_ID: C02VD909V08 #status-content-build
  NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
  BUILDTYPE: vagovprod
  DEPLOY_BUCKET: content.www.va.gov
  DRUPAL_ADDRESS: https://prod.cms.va.gov
  INSTANCE_TYPE: m6i.4xlarge
  MAXIMUM_HEAP: 5000
    # secrets.ACTIONS_RUNNER_DEBUG is set to 'true' when re-running a workflow with debug.
  ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}

jobs:
  validate-build-status:
    name: Validate Build Status
    runs-on: [self-hosted, asg]
    outputs:
      REF: ${{ steps.get-latest-release.outputs.target_commitish }}
      TAG: ${{ steps.get-latest-release.outputs.tag_name }}
      APPROX_WORKFLOW_START_TIME: ${{ steps.export-approx-workflow-start-time.outputs.APPROX_WORKFLOW_START_TIME }}
    timeout-minutes: 15

    steps:
      - name: Test Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1
