name: ZZ Content Release Workflow testing

on:
  workflow_dispatch:
  pull_request:

  # repository_dispatch:
  #   types: [content-release]



concurrency:
  group: content-release-node-limit

env:
  CMS_NOTIFICATIONS_SLACK: CJT90C0UT # cms-notifications
  VFS_PLATFORM_BUILDS_SLACK: C0MQ281DJ # vfs-platform-builds
  BROKEN_LINKS_SLACK: C030F5WV2TF # content-broken-links
  CONTENT_BUILD_CHANNEL_ID: C02VD909V08 #status-content-build
  NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
  BUILDTYPE: vagovstaging
  DEPLOY_BUCKET: staging.content.www.va.gov
  DRUPAL_ADDRESS: https://main-rufdsbo6qfzad8ds1x1anvitvwgjirbu.demo.cms.va.gov
  # Not a sensitive secret; used for our testing environments only, with systems
  # with sanitized databases.
  DRUPAL_PASSWORD: drupal8
  INSTANCE_TYPE: m6i.4xlarge
  MAXIMUM_HEAP: 5000



jobs:
  validate-build-status:
    name: Validate Build Status
    runs-on: self-hosted
    outputs:
      REF: ${{ steps.get-latest-release.outputs.target_commitish }}
      TAG: ${{ steps.get-latest-release.outputs.tag_name }}
      APPROX_WORKFLOW_START_TIME: ${{ steps.export-approx-workflow-start-time.outputs.APPROX_WORKFLOW_START_TIME }}
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/workflows/install
        # with:
        #   key: ${{ hashFiles('yarn.lock') }}
        #   yarn_cache_folder: ~/.cache/yarn
        #   path: |
        #     ~/.cache/yarn
        #     node_modules

      - name: Get latest release
        id: get-latest-release
        uses: ./.github/workflows/fetch-latest-release

      - name: Validate build status
        run: node ./script/github-actions/validate-build-status.js ${{ steps.get-latest-release.outputs.target_commitish }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
