name: Test CI Failure

on:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: content-build
    steps:
      - run: echo ::set-output name=buildtime::$(date +%s)
        working-directory: ${{ github.workspace }}
      - name: Checkout vagov-content
        uses: actions/checkout@v2
        with:
          repository: department-of-veterans-affairs/vagov-content
          path: vagov-content

      - name: Checkout content-build
        uses: actions/checkout@v2
        with:
          path: content-build
          ref: ${{ needs.set-env.outputs.REF }}
