name: Request Content Release

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Daily Production Release
    types:
      - completed

jobs:
  notify:
    name: Request Content Release
    runs-on:
      - self-hosted
      - linux
      - x64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Request a content release from the CMS
        uses: ./.github/workflows/authenticated-cms-request
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          url: https://prod.cms.va.gov/api/content_release/request_build
          method: GET
      
      - name: Print status
        shell: bash
        run: |
          echo "A build has been requested. It may take up to a minute for the workflow to be dispatched."
