name: Content Release

on:
  push:

jobs:
  start-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 70bbb6a6c30016a032cc88f5943b339e63e32d29
          token: ${{ secrets.FE_GITHUB_ACTION_PAT }}

      - name: Create tag
        run: git tag v0.0.1750 70bbb6a6c30016a032cc88f5943b339e63e32d29 && git push origin v0.0.1750

      # - name: Create release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v0.0.1750
      #     release_name: content-build/v0.0.1750
